### ISSUE TITLE
Fails to connect

### ISSUE THREAD

**Issue by dfaust** [Geal/lapin#28]
The future returned by `lapin::client::Client::connect` doesn't always complete.

In some instances when running something like the following code, the application will just stall.

```rust
core.run(
    TcpStream::connect(&addr, &handle).and_then(|stream| {
        lapin::client::Client::connect(stream, &ConnectionOptions::default())
    })
)
```

log file: https://www.dropbox.com/s/gti4kf327vfepib/log.html?dl=0

**Comment by Geal** [comment]
thanks, I'll look into it

**Comment by Geal** [comment]
I can see the issue, but I can rarely trigger it, what's your setup? How far is the amqp server?
I pushed a small fix in version 0.7.0, please try with this one, it might fix this issue.

**Comment by dfaust** [comment]
Since I have a lot of integration tests, I'm hitting this bug pretty much all the time.
I'm running RabbitMQ 3.6.9 locally in a docker container.

I have tested it with version 0.7.0 but the bug persists. In fact I think I found another one but I'll open a separate issue for it.

**Comment by dfaust** [comment]
I wasn't able to reproduce the output from #30 so here is another log for this issue but with a few more log statements (https://github.com/dfaust/lapin/blob/debug-log/futures/src/transport.rs#L192-L260), I hope it helps.

log file: https://www.dropbox.com/s/jfls4ikt5ci4hjs/conn_log_28.html?dl=0

**Comment by Keruspe** [comment]
@dfaust not sure that would change anything about this (Geal have some ideas on how to work around that) but could you give #31 a go?

**Comment by dfaust** [comment]
I checked a few failed tests using #31, this time I couldn't find any `ERRO did not get a frame? -> None`, so I posted the log to #30.
